INSERT INTO cliente(nombres, apellidos, direccion, email, celular) VALUES('Vidal', 'Cupe Quispe', 'Republica de Panama 4174', 'vidalcq2607@gmail.com', '967745565');
INSERT INTO cliente(nombres, apellidos, direccion, email, celular) VALUES('Juan', 'Perez Lopez', 'Av Argentina 2355', 'perez@gmail.com', '987456251');
INSERT INTO cliente(nombres, apellidos, direccion, email, celular) VALUES('Miguel', 'Suarez Gonzales', 'Av Peru 1234', 'suarez@gmail.com', '9087654671');
INSERT INTO cliente(nombres, apellidos, direccion, email, celular) VALUES('Marco', 'Martinez Pachas', 'Av Benavides 3456', 'pachas@gmail.com', '956780930');
INSERT INTO cliente(nombres, apellidos, direccion, email, celular) VALUES('Ricardo', 'Pachas lopez', 'Republica de Panama 4645', 'lopez@gmail.com', '924567092');
INSERT INTO cliente(nombres, apellidos, direccion, email, celular) VALUES('Jose', 'Rivas Jimenez', 'Republica de Panama 8976', 'rivas@gmail.com', '8738549932');
INSERT INTO cliente(nombres, apellidos, direccion, email, celular) VALUES('Juan', 'Espinoza', 'Republica de Panama 23', 'espinoza@gmail.com', '974756575');
INSERT INTO cliente(nombres, apellidos, direccion, email, celular) VALUES('Carlos', 'Saenz Soto', 'Republica de Panama 34', 'saenz@gmail.com', '967745123');
INSERT INTO cliente(nombres, apellidos, direccion, email, celular) VALUES('Martin', 'Rebosio', 'Republica de Panama 12', 'rebosio@gmail.com', '912345565');
INSERT INTO cliente(nombres, apellidos, direccion, email, celular) VALUES('Pedro', 'Lopez Suarez', 'Republica de Panama 34', 'lopesuarez@gmail.com', '913455565');
